### ISSUE TITLE
Unable to provide third party value extractor when the bean definition is not returning `ValueExtractor`

### ISSUE THREAD

**Issue by tobias-bahls** [micronaut-projects/micronaut-validation#253]
### Expected Behavior

When I create a Bean via Factory in order to provide [`JsonNullableJakartaValueExtractor`](https://github.com/OpenAPITools/jackson-databind-nullable/blob/8861f83253b2373288772a55f8fb3938fa4824b9/src/main/java/org/openapitools/jackson/nullable/JsonNullableJakartaValueExtractor.java#L11) like this:

```kotlin
@Factory
private class JsonNullableJakartaValueExtractorFactory {
    @Singleton
    fun nullableExtractor(): JsonNullableJakartaValueExtractor {
        return JsonNullableJakartaValueExtractor()
    }
}
```

I expect the ValueExtractor to be picked up by Jakarta Validation.

### Actual Behaviour

The registration of the value extractor throws an error:
```
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at io.micronaut.validation.validator.extractors.ValueExtractorDefinition.<init>(ValueExtractorDefinition.java:48)
	at io.micronaut.validation.validator.extractors.DefaultValueExtractors.<init>(DefaultValueExtractors.java:83)
	at io.micronaut.validation.validator.extractors.$DefaultValueExtractors$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
	... 76 common frames omitted
```

### Steps To Reproduce

See example

### Version

4.1.2

**Comment by tobias-bahls** [comment]
Found a workaround for this issue that fixes it for now by manually adding `JsonNullableJakartaValueExtractor` to `DefaultValidatorConfiguration` 
```kotlin
@Context
class JsonNullableValueExtractorRegistrar(private val config: DefaultValidatorConfiguration) {
    @PostConstruct
    fun registerJsonNullableValueExtractor() {
        config.addValueExtractor(JsonNullableJakartaValueExtractor())
    }
}

```

**Comment by yawkat** [comment]
sounds kind of like #258

**Comment by altro3** [comment]
@dstepanov @graemerocher can be closed. Already fixed
