### ISSUE TITLE
Unable to provide a ValueExtractor

### ISSUE THREAD

**Issue by loicmathieu** [micronaut-projects/micronaut-validation#432]
### Expected Behavior

We can provide our own value extractor

### Actual Behaviour

I have this value extractor:

```java
@Singleton
public class PropertyValueExtractor implements ValueExtractor<Property<@ExtractedValue ?>> {

    @Override
    public void extractValues(Property<?> originalValue, ValueReceiver receiver) {
        receiver.value( null, originalValue.getExpression() );
    }
}
```

Where `Property` is an holder for an expression, like `Optional` is for a value.
This value extractor mimic the standard `OptionalValueExtractor`.

When launching the application, it fails to start with the error:
```
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at io.micronaut.validation.validator.extractors.ValueExtractorDefinition.<init>(ValueExtractorDefinition.java:48)
	at io.micronaut.validation.validator.extractors.DefaultValueExtractors.<init>(DefaultValueExtractors.java:83)
	at io.micronaut.validation.validator.extractors.$DefaultValueExtractors$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
	... 70 more
```

### Version

4.6.3

**Comment by dstepanov** [comment]
Please provide a sample app

**Comment by loicmathieu** [comment]
Also tried with a factory, it didn't work either.

```java
@Factory
public class PropertyValueExtractorFactory {

    @Bean
    public ValueExtractor<Property<@ExtractedValue ?>> propertyValueExtractor() {
        return (originalValue, receiver) -> receiver.value( null, originalValue.getExpression() );
    }

}
```

```
Caused by: jakarta.validation.valueextraction.ValueExtractorDefinitionException: ValueExtractor definition 'io.kestra.core.models.property.PropertyValueExtractorFactory$$Lambda/0x00007b1eb097f518@749ab7b4' is missing @ExtractedValue!
	at io.micronaut.validation.validator.extractors.ValueExtractorDefinition.findExtractedValue(ValueExtractorDefinition.java:99)
	at io.micronaut.validation.validator.extractors.ValueExtractorDefinition.<init>(ValueExtractorDefinition.java:56)
	at io.micronaut.validation.validator.extractors.ValueExtractorDefinition.<init>(ValueExtractorDefinition.java:48)
	at io.micronaut.validation.validator.extractors.DefaultValueExtractors.<init>(DefaultValueExtractors.java:83)
	at io.micronaut.validation.validator.extractors.$DefaultValueExtractors$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
```

I'll provide a reproducer.

**Comment by loicmathieu** [comment]
Here is a reproducer: 
[value-extractor.zip](https://github.com/user-attachments/files/17576515/value-extractor.zip)

**Comment by dstepanov** [comment]
I fixed that in https://github.com/micronaut-projects/micronaut-validation/pull/424 and it works in 4.8.0

BTW:
```
    annotationProcessor "io.micronaut:micronaut-inject-java"
    annotationProcessor "io.micronaut.validation:micronaut-validation-processor"
    annotationProcessor "org.projectlombok:lombok:1.18.34"
```
Lombok always needs to be defined first!

**Comment by loicmathieu** [comment]
Thanks @dstepanov 

> Lombok always needs to be defined first!

We always define it first, it was an error in the reproducer.

**Comment by loicmathieu** [comment]
I confirm forcing `"io.micronaut.validation:micronaut-validation-bom:4.8.0"` works, thanks

**Comment by loicmathieu** [comment]
@dstepanov I comment too quickly.

Now my application starts, but the validator cannot be found:

```
jakarta.validation.ConstraintDeclarationException: HV000197: No value extractor found for type parameter 'T' of type io.kestra.core.models.property.Property.
	at org.hibernate.validator.internal.metadata.core.MetaConstraints.addValueExtractorDescriptorForTypeArgumentLocation(MetaConstraints.java:147)
	at org.hibernate.validator.internal.metadata.core.MetaConstraints.create(MetaConstraints.java:63)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findTypeUseConstraints(AnnotationMetaDataProvider.java:806)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findTypeArgumentsConstraints(AnnotationMetaDataProvider.java:776)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findTypeAnnotationConstraints(AnnotationMetaDataProvider.java:609)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findPropertyMetaData(AnnotationMetaDataProvider.java:241)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getFieldMetaData(AnnotationMetaDataProvider.java:229)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.retrieveBeanConfiguration(AnnotationMetaDataProvider.java:130)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getBeanConfiguration(AnnotationMetaDataProvider.java:121)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManagerImpl.getBeanConfigurationForHierarchy(BeanMetaDataManagerImpl.java:234)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManagerImpl.createBeanMetaData(BeanMetaDataManagerImpl.java:201)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManagerImpl.getBeanMetaData(BeanMetaDataManagerImpl.java:165)
	at org.hibernate.validator.internal.engine.ValidatorImpl.buildNewLocalExecutionContext(ValidatorImpl.java:772)
	at org.hibernate.validator.internal.engine.ValidatorImpl$CascadingValueReceiver.doValidate(ValidatorImpl.java:707)
	at org.hibernate.validator.internal.engine.ValidatorImpl$CascadingValueReceiver.indexedValue(ValidatorImpl.java:681)
	at org.hibernate.validator.internal.engine.valueextraction.ListValueExtractor.extractValues(ListValueExtractor.java:28)
	at org.hibernate.validator.internal.engine.valueextraction.ListValueExtractor.extractValues(ListValueExtractor.java:17)
	at org.hibernate.validator.internal.engine.valueextraction.ValueExtractorHelper.extractValues(ValueExtractorHelper.java:42)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedContainerElementsForCurrentGroup(ValidatorImpl.java:651)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraints(ValidatorImpl.java:598)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:409)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:172)
	at io.micronaut.configuration.hibernate.validator.MicronautHibernateValidator.validate(MicronautHibernateValidator.java:69)
```

I checked inside the ValueExtractorManager in a debug session and my validator is not here so it seems it has not been added by Micronaut.

**Comment by dstepanov** [comment]
This project is about Micronaut Validation, your trace is about Hibernate validation implementation

**Comment by loicmathieu** [comment]
Yes it didn't find the validator that micronaut should have registered

**Comment by dstepanov** [comment]
If that’s the issue that should be filled for the Micronaut Hibernate validation project

**Comment by loicmathieu** [comment]
OK, I'll do that
